default_language_version:
    python: python3.11

default_stages: [pre-commit, pre-push]

repos:
-   repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
    - id: black
-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    - id: isort
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
